/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppMain: typeof import("./../layout/components/AppMain.vue")["default"];
    BarChart: typeof import("./../views/dashboard/components/BarChart.vue")["default"];
    Breadcrumb: typeof import("./../components/Breadcrumb/index.vue")["default"];
    Dictionary: typeof import("./../components/Dictionary/index.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRate: typeof import("element-plus/es")["ElRate"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    FixedThead: typeof import("./../views/table/dynamic-table/components/FixedThead.vue")["default"];
    FunnelChart: typeof import("./../views/dashboard/components/FunnelChart.vue")["default"];
    GithubCorner: typeof import("./../components/GithubCorner/index.vue")["default"];
    Hamburger: typeof import("./../components/Hamburger/index.vue")["default"];
    IconSelect: typeof import("./../components/IconSelect/index.vue")["default"];
    IEpCaretBottom: typeof import("~icons/ep/caret-bottom")["default"];
    IEpClose: typeof import("~icons/ep/close")["default"];
    IEpDownload: typeof import("~icons/ep/download")["default"];
    IEpSetting: typeof import("~icons/ep/setting")["default"];
    LangSelect: typeof import("./../components/LangSelect/index.vue")["default"];
    Link: typeof import("./../layout/components/Sidebar/Link.vue")["default"];
    Logo: typeof import("./../layout/components/Sidebar/Logo.vue")["default"];
    MultiUpload: typeof import("./../components/Upload/MultiUpload.vue")["default"];
    Navbar: typeof import("./../layout/components/Navbar.vue")["default"];
    Pagination: typeof import("./../components/Pagination/index.vue")["default"];
    PieChart: typeof import("./../views/dashboard/components/PieChart.vue")["default"];
    RadarChart: typeof import("./../views/dashboard/components/RadarChart.vue")["default"];
    RightPanel: typeof import("./../components/RightPanel/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    ScrollPane: typeof import("./../layout/components/TagsView/ScrollPane.vue")["default"];
    Settings: typeof import("./../layout/components/Settings/index.vue")["default"];
    Sidebar: typeof import("./../layout/components/Sidebar/index.vue")["default"];
    SidebarItem: typeof import("./../layout/components/Sidebar/SidebarItem.vue")["default"];
    SingleUpload: typeof import("./../components/Upload/SingleUpload.vue")["default"];
    SizeSelect: typeof import("./../components/SizeSelect/index.vue")["default"];
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"];
    SwitchRoles: typeof import("./../views/permission/components/SwitchRoles.vue")["default"];
    TagInput: typeof import("./../components/TagInput/index.vue")["default"];
    TagsView: typeof import("./../layout/components/TagsView/index.vue")["default"];
    UnfixedThead: typeof import("./../views/table/dynamic-table/components/UnfixedThead.vue")["default"];
    WangEditor: typeof import("./../components/WangEditor/index.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
